export const ADD_ITEM_HOME = 'ADD_ITEM_HOME'
export const ADD_ITEM_CONTACT= 'ADD_ITEM_CONTACT'
export const INC_COUNTER="INC_COUNTER"
export const DELETE_ITEM="DELETE_ITEM"
//TYPE OF CAR 
export const ADD_CAR="ADD_CAR"
export const CAR_COUNTER="CAR_COUNTER"
export const DELETE_CAR = "DELETE_CAR"
